### ISSUE TITLE
Add Stack Trace for Typescript source.

### ISSUE THREAD

**Issue by wangzhihao** [MoonsetJS/Moonset#26]
Here is a typescript source stack trace for CDK:
```
Unable to resolve plugin aws-cdk-conduit2: Error: Cannot find module 'aws-cdk-conduit2'
Require stack:
- /workspace/amazon/COVID/src/COVIDWhitelist/node_modules/aws-cdk/bin/cdk.js
- /workspace/amazon/COVID/src/COVIDWhitelist/node_modules/aws-cdk/bin/cdk
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at tryResolve (/workspace/amazon/COVID/src/COVIDWhitelist/node_modules/aws-cdk/bin/cdk.ts:151:24)
    at loadPlugins (/workspace/amazon/COVID/src/COVIDWhitelist/node_modules/aws-cdk/bin/cdk.ts:141:26)
    at initCommandLine (/workspace/amazon/COVID/src/COVIDWhitelist/node_modules/aws-cdk/bin/cdk.ts:159:3)
Unable to resolve plug-in: aws-cdk-conduit2
```

We should also have typescript source stack trace. Currently our stack trace is for the compiled javascript code.

**Comment by wangzhihao** [comment]
https://github.com/evanw/node-source-map-support can be a good option.

**Comment by wangzhihao** [comment]
```
- /home/zhihaow/workspace/mine/Moonset/packages/executor/lib/plugin.js
- /home/zhihaow/workspace/mine/Moonset/packages/executor/lib/ir.js
- /home/zhihaow/workspace/mine/Moonset/packages/executor/lib/index.js
- /home/zhihaow/workspace/mine/Moonset/packages/cli/lib/moonset.js
- /home/zhihaow/workspace/mine/Moonset/packages/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at PluginHost.load (/home/zhihaow/workspace/mine/Moonset/packages/executor/lib/plugin.ts:59:22)
    at /home/zhihaow/workspace/mine/Moonset/packages/cli/lib/moonset.ts:56:29
    at Array.forEach (<anonymous>)
    at Moonset.loadPlugins (/home/zhihaow/workspace/mine/Moonset/packages/cli/lib/moonset.ts:55:15)
    at Moonset.run (/home/zhihaow/workspace/mine/Moonset/packages/cli/lib/moonset.ts:28:10)
    at Object.<anonymous> (/home/zhihaow/workspace/mine/Moonset/packages/cli/lib/moonset.ts:78:15)
```

**Comment by wangzhihao** [comment]
If the error happens in synth or deploy phase, I.E. sub-process. We still got JS error stack. See the following log:

```
=========================deploy

/home/gengli/live/src/Foo-Moonset-EDX
info: The plugins: @moonset/plugin-platform-emr,/home/gengli/live/src/Foo-Moonset-EDX. The hooks: platform.emr.init,platform.emr.task,data.edx.init,data.edx.import,data.edx.export, The tasks: {"hive":"emr","spark":"emr"} {"service":"user-service"}
(node:7836) ExperimentalWarning: The fs.promises API is experimental
{ edx:
   { provider: 'etlm',
     subject: 'fba-space-robot-marketplace-information-xml',
     datasetName: 'r-2-daily',
     datasetKey: '2020-04-17',
     dbName: 'foo',
     tableName: 'foo1' } }
{ provider: 'etlm',
  subject: 'fba-space-robot-marketplace-information-xml',
  datasetName: 'r-2-daily',
  datasetKey: '2020-04-17',
  dbName: 'foo',
  tableName: 'foo1',
  isImport: true,
  edxAgentLambda:
   Function {
     node: ConstructNode { _actualNode: [Node] },
     stack:
      Stack {
        node: [ConstructNode],
        templateOptions: {},
        _stackDependencies: {},
        _missingContext: [],
        addedImageAssets: Set {},
        _logicalIds: [LogicalIDs],
        account: '209302747524',
        region: 'us-east-1',
        environment: 'aws://209302747524/us-east-1',
        terminationProtection: undefined,
        _stackName: 'MoonsetEDXStack',
        tags: [TagManager],
        artifactId: 'MoonsetEDXStack',
        templateFile: 'MoonsetEDXStack.template.json',
        _assetParameters: [Construct],
        edxAgentLambda: [Circular],
        edxS3BucketName: 'moonset-edx',
        conexioJarS3Path:
         's3://${Token[TOKEN.160]}/${Token[TOKEN.163]}${Token[TOKEN.165]}',
        [Symbol(@aws-cdk/core.DependableTrait)]: [Object] },
     _physicalName: undefined,
     _allowCrossEnvironment: false,
     physicalName: '${Token[TOKEN.127]}',
     permissionsNode: ConstructNode { _actualNode: [Node] },
     canCreatePermissions: true,
     layers: [],
     environment: {},
     role:
      Role {
        node: [ConstructNode],
        stack: [Stack],
        _physicalName: undefined,
        _allowCrossEnvironment: false,
        physicalName: '${Token[TOKEN.113]}',
        grantPrincipal: [Circular],
        assumeRoleAction: 'sts:AssumeRole',
        managedPolicies: [Array],
        attachedPolicies: [AttachedPolicies],
        assumeRolePolicy: [PolicyDocument],
        permissionsBoundary: undefined,
        roleId: '${Token[TOKEN.118]}',
        roleArn: '${Token[TOKEN.119]}',
        roleName: '${Token[TOKEN.121]}',
        policyFragment: [PrincipalPolicyFragment],
        defaultPolicy: [Policy],
        [Symbol(@aws-cdk/core.DependableTrait)]: [Object] },
     grantPrincipal:
      Role {
        node: [ConstructNode],
        stack: [Stack],
        _physicalName: undefined,
        _allowCrossEnvironment: false,
        physicalName: '${Token[TOKEN.113]}',
        grantPrincipal: [Circular],
        assumeRoleAction: 'sts:AssumeRole',
        managedPolicies: [Array],
        attachedPolicies: [AttachedPolicies],
        assumeRolePolicy: [PolicyDocument],
        permissionsBoundary: undefined,
        roleId: '${Token[TOKEN.118]}',
        roleArn: '${Token[TOKEN.119]}',
        roleName: '${Token[TOKEN.121]}',
        policyFragment: [PrincipalPolicyFragment],
        defaultPolicy: [Policy],
        [Symbol(@aws-cdk/core.DependableTrait)]: [Object] },
     deadLetterQueue: undefined,
     functionName: '${Token[TOKEN.143]}',
     functionArn: '${Token[TOKEN.144]}',
     runtime:
      Runtime { name: 'java8', supportsInlineCode: false, family: 1 },
     currentVersionOptions: undefined,
     [Symbol(@aws-cdk/core.DependableTrait)]: { dependencyRoots: [Array] } },
  conexioJarS3Path:
   's3://${Token[TOKEN.160]}/${Token[TOKEN.163]}${Token[TOKEN.165]}',
  emrEDXPublicKeyName: 'edx.public.key-${Token[EmrSettings.ClusterId.167]}',
  edxS3BucketName: 'moonset-edx' }
/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:186
        throw new Error(`Field references must be the entire string, cannot concatenate them (found '${x}')`);
        ^

Error: Field references must be the entire string, cannot concatenate them (found '--public-key-path=edx.public.key-${Token[EmrSettings.ClusterId.167]}')
    at jsonPathString (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:186:15)
    at arr.map.value (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:114:47)
    at Array.map (<anonymous>)
    at recurseArray (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:113:20)
    at recurseObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:85:32)
    at recurseObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:94:24)
    at recurseObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:94:24)
    at Object.renderObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:30:12)
    at Function.renderObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/fields.js:102:28)
    at Task.toStateJson (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/states/task.js:68:74)
Subprocess exited with error 1
(node:7790) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: /local/home/gengli/.npm/_npx/7790/lib/node_modules/moonset/node_modules/aws-cdk/bin/cdk synth --app="node /local/home/gengli/.npm/_npx/7790/lib/node_modules/moonset/node_modules/@moonset/executor/lib/cdk/moonset-app.js" --output=build/cdk.out/
(node:7836) ExperimentalWarning: The fs.promises API is experimental
/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:186
        throw new Error(`Field references must be the entire string, cannot concatenate them (found '${x}')`);
        ^

Error: Field references must be the entire string, cannot concatenate them (found '--public-key-path=edx.public.key-${Token[EmrSettings.ClusterId.167]}')
    at jsonPathString (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:186:15)
    at arr.map.value (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:114:47)
    at Array.map (<anonymous>)
    at recurseArray (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:113:20)
    at recurseObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:85:32)
    at recurseObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:94:24)
    at recurseObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:94:24)
    at Object.renderObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:30:12)
    at Function.renderObject (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/fields.js:102:28)
    at Task.toStateJson (/local/home/gengli/live/src/Foo-Moonset-EDX/node_modules/@aws-cdk/aws-stepfunctions/lib/states/task.js:68:74)
Subprocess exited with error 1
{ edx:
   { provider: 'etlm',
     subject: 'fba-space-robot-marketplace-information-xml',
     datasetName: 'r-2-daily',
     datasetKey: '2020-04-17',
     dbName: 'foo',
     tableName: 'foo1' } }
{ provider: 'etlm',
  subject: 'fba-space-robot-marketplace-information-xml',
  datasetName: 'r-2-daily',
  datasetKey: '2020-04-17',
  dbName: 'foo',
  tableName: 'foo1',
  isImport: true,
  edxAgentLambda:
   Function {
     node: ConstructNode { _actualNode: [Node] },
     stack:
      Stack {
        node: [ConstructNode],
        templateOptions: {},
        _stackDependencies: {},
        _missingContext: [],
        addedImageAssets: Set {},
        _logicalIds: [LogicalIDs],
        account: '209302747524',
        region: 'us-east-1',
        environment: 'aws://209302747524/us-east-1',
        terminationProtection: undefined,
        _stackName: 'MoonsetEDXStack',
        tags: [TagManager],
        artifactId: 'MoonsetEDXStack',
        templateFile: 'MoonsetEDXStack.template.json',
        _assetParameters: [Construct],
        edxAgentLambda: [Circular],
        edxS3BucketName: 'moonset-edx',
        conexioJarS3Path:
         's3://${Token[TOKEN.160]}/${Token[TOKEN.163]}${Token[TOKEN.165]}',
        [Symbol(@aws-cdk/core.DependableTrait)]: [Object] },
     _physicalName: undefined,
     _allowCrossEnvironment: false,
     physicalName: '${Token[TOKEN.127]}',
     permissionsNode: ConstructNode { _actualNode: [Node] },
     canCreatePermissions: true,
     layers: [],
     environment: {},
     role:
      Role {
        node: [ConstructNode],
        stack: [Stack],
        _physicalName: undefined,
        _allowCrossEnvironment: false,
        physicalName: '${Token[TOKEN.113]}',
        grantPrincipal: [Circular],
        assumeRoleAction: 'sts:AssumeRole',
        managedPolicies: [Array],
        attachedPolicies: [AttachedPolicies],
        assumeRolePolicy: [PolicyDocument],
        permissionsBoundary: undefined,
        roleId: '${Token[TOKEN.118]}',
        roleArn: '${Token[TOKEN.119]}',
        roleName: '${Token[TOKEN.121]}',
        policyFragment: [PrincipalPolicyFragment],
        defaultPolicy: [Policy],
        [Symbol(@aws-cdk/core.DependableTrait)]: [Object] },
     grantPrincipal:
      Role {
        node: [ConstructNode],
        stack: [Stack],
        _physicalName: undefined,
        _allowCrossEnvironment: false,
        physicalName: '${Token[TOKEN.113]}',
        grantPrincipal: [Circular],
        assumeRoleAction: 'sts:AssumeRole',
        managedPolicies: [Array],
        attachedPolicies: [AttachedPolicies],
        assumeRolePolicy: [PolicyDocument],
        permissionsBoundary: undefined,
                          'sudo',
                          'aws',
                          'sudo',
                          'aws',
                          'sudo',
        roleId: '${Token[TOKEN.118]}',
        roleArn: '${Token[TOKEN.119]}',
        roleName: '${Token[TOKEN.121]}',
        policyFragment: [PrincipalPolicyFragment],
        defaultPolicy: [Policy],
        [Symbol(@aws-cdk/core.DependableTrait)]: [Object] },
     deadLetterQueue: undefined,
     functionName: '${Token[TOKEN.143]}',
     functionArn: '${Token[TOKEN.144]}',
     runtime:
      Runtime { name: 'java8', supportsInlineCode: false, family: 1 },
     currentVersionOptions: undefined,
     [Symbol(@aws-cdk/core.DependableTrait)]: { dependencyRoots: [Array] } },
  conexioJarS3Path:
   's3://${Token[TOKEN.160]}/${Token[TOKEN.163]}${Token[TOKEN.165]}',
  emrEDXPublicKeyName: 'edx.public.key-${Token[EmrSettings.ClusterId.167]}',
  edxS3BucketName: 'moonset-edx' }
    at makeError (/local/home/gengli/.npm/_npx/7790/lib/node_modules/moonset/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/local/home/gengli/.npm/_npx/7790/lib/node_modules/moonset/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:7790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7790) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
